name: "test"

on:
 workflow_dispatch:
 push:

jobs:
  test:
    name: "build test"
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # - name: Cache LLVM and Clang
    #   id: cache-llvm
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ runner.temp }}/llvm
    #     key: llvm-15.0
    # - name: Install LLVM and Clang
    #   uses: KyleMayes/install-llvm-action@v1
    #   with:
    #     version: "15.0"
    #     directory: ${{ runner.temp }}/llvm
    #     cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-llvm
          mingw-w64-x86_64-gcc
        location: ${{ runner.temp }}
    - name: build with gcc win
      env:
        cc: ${{ runner.temp }}\msys64\mingw64\bin\gcc.exe
        cxx: ${{ runner.temp }}\msys64\mingw64\bin\g++.exe
      run: cd cpp && cmake -G "Ninja Multi-Config" . && cmake --build . --target LoaderNative
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - name: Setup Memory Environment on Windows
      run: >
        wmic pagefileset where name="D:\\pagefile.sys" set InitialSize=1024,MaximumSize=9216
      shell: cmd
      continue-on-error: true
    - name: replace llvm
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: ${{ github.workspace }}/kotlin/build.gradle.kts
        oldString: LLVM_REPLACE_FOR_GITHUB_WORKFLOW
        newString: ${{ runner.temp }}\msys64\mingw64
        showFileContent: true
        escapeBackslash: true
    - name: replace lib path of def file
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: ${{ github.workspace }}/kotlin/src/nativeInterop/cinterop/lib.def
        oldString: GITHUB_WORKSPACE
        newString: ${{ github.workspace }}/cpp
        showFileContent: true
        escapeBackslash: true
    - name: replace header path of def file
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: ${{ github.workspace }}/kotlin/src/nativeInterop/cinterop/lib.def
        oldString: GITHUB_KTHEADER
        newString: ${{ github.workspace }}/kotlin/src/nativeInterop/cinterop
        showFileContent: true
        escapeBackslash: true
    # - name: replace header path of def file
    #   uses: Nambers/ReplaceStringInFile@v1.3
    #   with:
    #     path: ${{ github.workspace }}/kotlin/src/nativeInterop/cinterop/lib.def
    #     oldString: libA.a
    #     newString: libA.a
    #     newStringWin: libA.lib
    #     showFileContent: true
    - name: run native
      run:  cd ./kotlin/ && ./gradlew :runDebugExecutableNative --warning-mode all --info --stacktrace
    